fix build with gcc >= 14
Add missing includes to avoid the following build failure with gcc >=
14:

codec_skeleton.c: In function 'skeleton_process_fisbone_message_header':
codec_skeleton.c:119:9: error: implicit declaration of function 'utf8_decode' [-Wimplicit-function-declaration]
  119 |     if (utf8_decode(header, &decoded) < 0) {
      |         ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/bb5d56d836e7d0f2a62daa9954878ad6e0b190ed

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>